use UNIVER
select * from FACULTY
select * from GROUPS
select * from STUDENT
select * from PROGRESS

----------------------------------------Task_1-----------------------------------------

-----без rollup:

select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, avg(PROGRESS.NOTE) [Average mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ТОВ')
group by FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT;

-----с rollup:

select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, avg(PROGRESS.NOTE) [Average mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ТОВ')
group by rollup(FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT);

----------------------------------------Task_2-----------------------------------------

select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, avg(PROGRESS.NOTE) [Average mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ТОВ')
group by cube(FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT);

----------------------------------------Task_3-----------------------------------------

select * from GROUPS
select * from STUDENT
select * from PROGRESS

-----с union:

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ТОВ')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
union
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ХТИТ')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY

-----с union all:

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ТОВ')
GROUP BY GROUPS.PROFESSI9ON, PROGRESS.SUBJECT, GROUPS.FACULTY
union all
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ХТИТ')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY

----------------------------------------Task_4-----------------------------------------
-----с intersect:

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ТОВ')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
intersect
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ХТИТ')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY

----------------------------------------Task_5-----------------------------------------
-----с except:

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ТОВ')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
except
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
    FACULTY.FACULTY in (N'ХТИТ')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY

----------------------------------------Task_6-----------------------------------------